dynamodb_table_name = "FlightSyteAlerts"

flight_search_lambda_function_name = "flightSearch"
writer_lambda_function_name        = "flightAlertsWriter"
reader_lambda_function_name        = "flightAlertsReader"
delete_lambda_function_name        = "flightAlertsDeleter"
processor_lambda_function_name     = "flightAlertsProcessor"
chatbot_lambda_function_name       = "flightChatbot"
subscribe_lambda_function_name     = "flightAlertsSubscriber"

flight_search_iam_policy_name = "LimitedFlightSearch"
writer_iam_policy_name        = "LimitedDynamoWrite"
reader_iam_policy_name        = "LimitedDynamoRead"
delete_iam_policy_name        = "LimitedDynamoDelete"
processor_iam_policy_name     = "LimitedFlightProcessor"
chatbot_iam_policy_name       = "LimitedChatbotAccess"
subscribe_iam_policy_name     = "LimitedSubscriber"

flight_search_assume_role = "flight-searcher"
writer_assume_role        = "flight-alert-writer"
reader_assume_role        = "flight-alert-reader"
delete_assume_role        = "flight-alert-deleter"
processor_assume_role     = "flight-alert-processor"
chatbot_assume_role       = "flight-chatbot-processor"
subscribe_assume_role     = "flight-alert-subscriber"

amadeus_cities_endpoint        = "https://test.api.amadeus.com/v1/reference-data/locations/cities"
amadeus_flight_offers_endpoint = "https://test.api.amadeus.com/v2/shopping/flight-offers"
amadeus_locations_endpoint     = "https://test.api.amadeus.com/v1/reference-data/locations"
amadeus_token_endpoint         = "https://test.api.amadeus.com/v1/security/oauth2/token"
gemini_ai_model                = "gemini-2.5-flash"